---
- name: install application
  hosts: localhost
  connection: local # use the localhost instead of an ssh connection

  tasks:
    - name: get jar file name
      command: ls /var/jenkins_home/app_build/
      register: jar_file_path

    - debug: var=jar_file_path.stdout_lines

    - name: build and docker application
      community.docker.docker_image:
        name: pmsolfest/project1.1-application
        state: present 
        source: build
        build:
          dockerfile: DockerFile
          path: /var/jenkins_home/app_build
        tag: slp1.1
        push: yes
    - name: install application
      community.docker.docker_container:
        name: my_webapp
        image: pmsolfest/project1.1-application:slp1.1
        state: started
        published_ports:
          - 56324:56324
